language: node_js

node_js:
  - node
  # 4 is stable on Gentoo/node LTS. So keeping support with that is worth it.
  - 4

sudo: required
dist: trusty

before_install:
  # https://launchpad.net/~thomas-schiex/+archive/ubuntu/blender
  - sudo add-apt-repository ppa:thomas-schiex/blender -y
  - sudo apt-get update
  - sudo apt-get install blender wget -y
before_script:
  - bin/node-babylonjs-blender-install.js
